stages:
  train_model:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/interim/tokenized_train.txt
      - data/interim/tokenized_val.txt
      - data/interim/encoded_train_labels.txt
      - data/interim/encoded_val_labels.txt
    params:
      - loss_function
      - optimizer
      - batch_train
      - batch_test
      - categories
      - epoch
      - embedding_dimension
    outs:
      - models/model.keras
    metrics:
      - reports/metrics.json
    plots:
      - reports/loss_plot.svg
    
  test_model:
    cmd: python src/test_model.py
    deps:
      - src/test_model.py
      - data/interim/test_features.txt
      - data/interim/test_labels.txt
      - models/model.keras
    outs:
      - reports/test_accuracy.txt
      - reports/test_loss.txt
      - reports/classification_report.txt
      - reports/confusion_matrix.txt
